In [1]:
import os
import time
import numpy as np
import pandas as pd

In [2]:
START_TIME = time.time()

BASE_URL = "https://datasets.imdbws.com/"

FILES_IMDB = {
    "tit_bas": "title.basics.tsv",
    "tit_rate": "title.ratings.tsv",
    "name_bas": "name.basics.tsv",
    "cast_crew": "title.principals.tsv",
}

FILES_HAND = {
    "add_seen": "add_movies_seen.txt",
    "add_unseen": "add_movies_unseen.txt",
    "add_secop": "add_movies_second_opinion.txt",
    "raw_status": "raw_status.xlsx"
}

FILES_GENERATED = {
    "films_raw": os.path.join("data", "generated", "films_raw.pkl"),
    "films_readable": os.path.join("data", "generated", "films_reading.xlsx"),
    "films_mining": os.path.join("data", "generated", "films_mining.xlsx")
}

In [3]:
raw_film_data = pd.read_pickle(FILES_GENERATED["films_raw"])

In [4]:
raw_film_data

,tconst,watched,watched_date,netflix,prime,enjoyment,priority,titleType,primaryTitle,originalTitle,...,numVotes,ordering,nconst,category,job,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,tt0015324,False,NaT,<NA>,<NA>,NaN,NaN,movie,Sherlock Jr.,Sherlock Jr.,...,51213,10,nm0504380,cinematographer,NaN,Elgin Lessley,1883,1944,cinematographer,tt0016332
1,tt0015324,False,NaT,<NA>,<NA>,NaN,NaN,movie,Sherlock Jr.,Sherlock Jr.,...,51213,10,nm0504380,cinematographer,NaN,Elgin Lessley,1883,1944,cinematographer,tt0015163
2,tt0015324,False,NaT,<NA>,<NA>,NaN,NaN,movie,Sherlock Jr.,Sherlock Jr.,...,51213,10,nm0504380,cinematographer,NaN,Elgin Lessley,1883,1944,cinematographer,tt0014341
3,tt0015324,False,NaT,<NA>,<NA>,NaN,NaN,movie,Sherlock Jr.,Sherlock Jr.,...,51213,10,nm0504380,cinematographer,NaN,Elgin Lessley,1883,1944,cinematographer,tt0015324
4,tt0015324,False,NaT,<NA>,<NA>,NaN,NaN,movie,Sherlock Jr.,Sherlock Jr.,...,51213,10,nm0504380,cinematographer,NaN,Elgin Lessley,1883,1944,actor,tt0016332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71987,tt9806192,True,NaT,<NA>,<NA>,4.0,NaN,movie,I Lost My Body,J'ai perdu mon corps,...,34081,6,nm0491011,writer,adaptation and dialogue,Guillaume Laurant,1961,<NA>,writer,tt0344510
71988,tt9806192,True,NaT,<NA>,<NA>,4.0,NaN,movie,I Lost My Body,J'ai perdu mon corps,...,34081,6,nm0491011,writer,adaptation and dialogue,Guillaume Laurant,1961,<NA>,actor,tt1149361
71989,tt9806192,True,NaT,<NA>,<NA>,4.0,NaN,movie,I Lost My Body,J'ai perdu mon corps,...,34081,6,nm0491011,writer,adaptation and dialogue,Guillaume Laurant,1961,<NA>,actor,tt0211915
71990,tt9806192,True,NaT,<NA>,<NA>,4.0,NaN,movie,I Lost My Body,J'ai perdu mon corps,...,34081,6,nm0491011,writer,adaptation and dialogue,Guillaume Laurant,1961,<NA>,actor,tt9806192
71991,tt9806192,True,NaT,<NA>,<NA>,4.0,NaN,movie,I Lost My Body,J'ai perdu mon corps,...,34081,6,nm0491011,writer,adaptation and dialogue,Guillaume Laurant,1961,<NA>,actor,tt0344510

In [9]:
# reformat staff age data into 1 column and make columns from the categories
staff = raw_film_data.loc[:,['tconst','nconst','category','primaryName','birthYear','deathYear']].drop_duplicates()
staff.loc[:,'printname'] = staff.loc[:,'primaryName'] + " " + staff.loc[:,'birthYear'].astype('str') + ' - ' + staff.loc[:,'deathYear'].astype(str)
staff.drop(['nconst','primaryName','birthYear','deathYear'], axis=1, inplace=True)
staff = staff.groupby(['tconst','category'])['printname'].aggregate(lambda x: tuple(x)).unstack()
staff.drop(['archive_footage','self','production_designer'], axis=1, inplace=True)
staff

category,actor,actress,cinematographer,composer,director,editor,producer,writer
tconst,,,,,,,,
tt0015324,"(Buster Keaton 1895 - 1966, Joe Keaton 1867 - ...","(Kathryn McGuire 1903 - 1978,)","(Elgin Lessley 1883 - 1944, Byron Houck 1891 -...","(Club Foot Orchestra <NA> - <NA>,)","(Buster Keaton 1895 - 1966,)",NaN,NaN,"(Jean C. Havez 1872 - 1925, Joseph A. Mitchell..."
tt0017136,"(Alfred Abel 1879 - 1937, Gustav Fröhlich 1902...","(Brigitte Helm 1906 - 1996,)",NaN,"(Sandro Forte 1970 - 2020, Maximianno Cobra 19...","(Fritz Lang 1890 - 1976,)",NaN,"(Erich Pommer 1889 - 1966,)","(Thea von Harbou 1888 - 1954, Fritz Lang 1890 ..."
tt0022100,"(Peter Lorre 1904 - 1964, Otto Wernicke 1893 -...","(Ellen Widmann 1894 - 1985, Inge Landgut 1922 ...","(Fritz Arno Wagner 1894 - 1958,)",NaN,"(Fritz Lang 1890 - 1976,)","(Paul Falkenberg 1903 - 1986,)",NaN,"(Thea von Harbou 1888 - 1954, Fritz Lang 1890 ..."
tt0025316,"(Jameson Thomas 1888 - 1939, Clark Gable 1901 ...","(Claudette Colbert 1903 - 1996,)","(Joseph Walker 1892 - 1985,)",NaN,"(Frank Capra 1897 - 1991,)","(Gene Havlick 1894 - 1959,)",NaN,"(Robert Riskin 1897 - 1955, Samuel Hopkins Ada..."
tt0031381,"(Clark Gable 1901 - 1960, Thomas Mitchell 1892...","(Vivien Leigh 1913 - 1967, Barbara O'Neil 1910...",NaN,NaN,"(Victor Fleming 1889 - 1949, George Cukor 1899...",NaN,NaN,"(Margaret Mitchell 1900 - 1949, Sidney Howard ..."
...,...,...,...,...,...,...,...,...
tt9691136,"(Nick Robinson 1995 - <NA>, Beulah Koale <NA> ...","(Chloë Grace Moretz 1997 - <NA>,)",NaN,NaN,"(Roseanne Liang <NA> - <NA>,)",NaN,"(Kelly McCormick 1977 - <NA>, Fred Berger <NA>...","(Max Landis 1985 - <NA>, Roseanne Liang <NA> -..."
tt9731598,"(Billy Eichner 1978 - <NA>, Luke Macfarlane 19...",NaN,"(Brandon Trost 1981 - <NA>,)","(Marc Shaiman 1959 - <NA>,)","(Nicholas Stoller 1976 - <NA>,)","(Daniel Gabbe <NA> - <NA>,)","(Judd Apatow 1967 - <NA>, Josh Church <NA> - <...","(Billy Eichner 1978 - <NA>, Nicholas Stoller 1..."
tt9764362,"(Ralph Fiennes 1962 - <NA>, Nicholas Hoult 198...","(Anya Taylor-Joy 1996 - <NA>, Hong Chau 1979 -...",NaN,NaN,"(Mark Mylod <NA> - <NA>,)",NaN,"(Betsy Koch <NA> - <NA>, Will Ferrell 1967 - <...","(Seth Reiss <NA> - <NA>, Will Tracy <NA> - <NA>)"
tt9783600,"(Chris Hemsworth 1983 - <NA>, Miles Teller 198...","(Jurnee Smollett 1986 - <NA>,)",NaN,NaN,"(Joseph Kosinski 1974 - <NA>,)",NaN,"(Tommy Harper <NA> - <NA>, Agnes Chu <NA> - <NA>)","(George Saunders <NA> - <NA>, Rhett Reese <NA>..."
tt9806192,"(Hakim Faris <NA> - <NA>, Patrick d'Assumçao <...","(Victoire Du Bois <NA> - <NA>,)",NaN,"(Dan Levy 1976 - <NA>,)","(Jérémy Clapin 1974 - <NA>,)","(Benjamin Massoubre <NA> - <NA>,)","(Marc Du Pontavice <NA> - <NA>,)","(Jérémy Clapin 1974 - <NA>, Guillaume Laurant ..."

In [11]:
# make all genres into columns for easy filtering in excel
genres = raw_film_data.loc[:,['tconst','genres']].drop_duplicates()
genres.genres = genres.genres.str.split(',')
genres = genres.explode('genres')
genres['value'] = 1
genres = pd.pivot_table(genres.explode('genres'), values='value', index='tconst', columns='genres', fill_value=0)
genres

genres,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,Music,Musical,Mystery,Romance,Sci-Fi,Short,Sport,Thriller,War,Western
tconst,,,,,,,,,,,,,,,,,,,,,
tt0015324,1,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
tt0017136,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
tt0022100,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
tt0025316,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
tt0031381,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt9691136,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
tt9731598,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
tt9764362,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
tt9783600,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
tt9806192,0,0,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [16]:
# remove old data and add new data to the movies
readable_data = raw_film_data.copy()
readable_data.drop(['isAdult','ordering', 'nconst','category','job','primaryName','birthYear','deathYear', 'genres','endYear','primaryProfession', 'knownForTitles'], axis=1, inplace=True)
readable_data.drop_duplicates(inplace=True)
readable_data = pd.merge(readable_data, genres, on="tconst", how="left")
readable_data = pd.merge(readable_data, staff, on="tconst", how="left")
readable_data.loc[:,'watched'] = readable_data.loc[:,'watched'].replace(True,1).replace(False,0)
readable_data
# readable_data.sort_values(by=['watched', 'averageRating'], ascending=False).to_excel(output_path, index=False)

,tconst,watched,watched_date,netflix,prime,enjoyment,priority,titleType,primaryTitle,originalTitle,...,War,Western,actor,actress,cinematographer,composer,director,editor,producer,writer
0,tt0015324,0,NaT,<NA>,<NA>,NaN,NaN,movie,Sherlock Jr.,Sherlock Jr.,...,0,0,"(Buster Keaton 1895 - 1966, Joe Keaton 1867 - ...","(Kathryn McGuire 1903 - 1978,)","(Elgin Lessley 1883 - 1944, Byron Houck 1891 -...","(Club Foot Orchestra <NA> - <NA>,)","(Buster Keaton 1895 - 1966,)",NaN,NaN,"(Jean C. Havez 1872 - 1925, Joseph A. Mitchell..."
1,tt0017136,0,NaT,0,0,NaN,NaN,movie,Metropolis,Metropolis,...,0,0,"(Alfred Abel 1879 - 1937, Gustav Fröhlich 1902...","(Brigitte Helm 1906 - 1996,)",NaN,"(Sandro Forte 1970 - 2020, Maximianno Cobra 19...","(Fritz Lang 1890 - 1976,)",NaN,"(Erich Pommer 1889 - 1966,)","(Thea von Harbou 1888 - 1954, Fritz Lang 1890 ..."
2,tt0022100,0,NaT,0,0,NaN,NaN,movie,M,M - Eine Stadt sucht einen Mörder,...,0,0,"(Peter Lorre 1904 - 1964, Otto Wernicke 1893 -...","(Ellen Widmann 1894 - 1985, Inge Landgut 1922 ...","(Fritz Arno Wagner 1894 - 1958,)",NaN,"(Fritz Lang 1890 - 1976,)","(Paul Falkenberg 1903 - 1986,)",NaN,"(Thea von Harbou 1888 - 1954, Fritz Lang 1890 ..."
3,tt0025316,0,NaT,<NA>,<NA>,NaN,NaN,movie,It Happened One Night,It Happened One Night,...,0,0,"(Jameson Thomas 1888 - 1939, Clark Gable 1901 ...","(Claudette Colbert 1903 - 1996,)","(Joseph Walker 1892 - 1985,)",NaN,"(Frank Capra 1897 - 1991,)","(Gene Havlick 1894 - 1959,)",NaN,"(Robert Riskin 1897 - 1955, Samuel Hopkins Ada..."
4,tt0031381,0,NaT,<NA>,<NA>,NaN,NaN,movie,Gone with the Wind,Gone with the Wind,...,1,0,"(Clark Gable 1901 - 1960, Thomas Mitchell 1892...","(Vivien Leigh 1913 - 1967, Barbara O'Neil 1910...",NaN,NaN,"(Victor Fleming 1889 - 1949, George Cukor 1899...",NaN,NaN,"(Margaret Mitchell 1900 - 1949, Sidney Howard ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,tt9691136,0,NaT,0,0,NaN,NaN,movie,Shadow in the Cloud,Shadow in the Cloud,...,1,0,"(Nick Robinson 1995 - <NA>, Beulah Koale <NA> ...","(Chloë Grace Moretz 1997 - <NA>,)",NaN,NaN,"(Roseanne Liang <NA> - <NA>,)",NaN,"(Kelly McCormick 1977 - <NA>, Fred Berger <NA>...","(Max Landis 1985 - <NA>, Roseanne Liang <NA> -..."
613,tt9731598,0,NaT,0,0,NaN,NaN,movie,Bros,Bros,...,0,0,"(Billy Eichner 1978 - <NA>, Luke Macfarlane 19...",NaN,"(Brandon Trost 1981 - <NA>,)","(Marc Shaiman 1959 - <NA>,)","(Nicholas Stoller 1976 - <NA>,)","(Daniel Gabbe <NA> - <NA>,)","(Judd Apatow 1967 - <NA>, Josh Church <NA> - <...","(Billy Eichner 1978 - <NA>, Nicholas Stoller 1..."
614,tt9764362,1,NaT,0,0,4.0,NaN,movie,The Menu,The Menu,...,0,0,"(Ralph Fiennes 1962 - <NA>, Nicholas Hoult 198...","(Anya Taylor-Joy 1996 - <NA>, Hong Chau 1979 -...",NaN,NaN,"(Mark Mylod <NA> - <NA>,)",NaN,"(Betsy Koch <NA> - <NA>, Will Ferrell 1967 - <...","(Seth Reiss <NA> - <NA>, Will Tracy <NA> - <NA>)"
615,tt9783600,1,NaT,<NA>,<NA>,4.0,NaN,movie,Spiderhead,Spiderhead,...,0,0,"(Chris Hemsworth 1983 - <NA>, Miles Teller 198...","(Jurnee Smollett 1986 - <NA>,)",NaN,NaN,"(Joseph Kosinski 1974 - <NA>,)",NaN,"(Tommy Harper <NA> - <NA>, Agnes Chu <NA> - <NA>)","(George Saunders <NA> - <NA>, Rhett Reese <NA>..."
616,tt9806192,1,NaT,<NA>,<NA>,4.0,NaN,movie,I Lost My Body,J'ai perdu mon corps,...,0,0,"(Hakim Faris <NA> - <NA>, Patrick d'Assumçao <...","(Victoire Du Bois <NA> - <NA>,)",NaN,"(Dan Levy 1976 - <NA>,)","(Jérémy Clapin 1974 - <NA>,)","(Benjamin Massoubre <NA> - <NA>,)","(Marc Du Pontavice <NA> - <NA>,)","(Jérémy Clapin 1974 - <NA>, Guillaume Laurant ..."